server {
    listen 80;
    server_name localhost;

    # Папка с файлами
    root /usr/share/nginx/html;
    index index.html;

    # Отдаём статические файлы
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Кэширование статики
    location ~* \.(css|js|png|jpg|svg|woff2?)$ {
        expires 7d;
        add_header Cache-Control "public, immutable";
    }

    # Не кэшировать HTML (чтобы изменения сразу подхватывались)
    location ~* \.html$ {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
    }
}