services:
  postgres:
    image: postgres:16-alpine
    container_name: flipcount-db
    environment:
      POSTGRES_DB: flipcount
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2507
    ports:
      - "5432:5432"
    volumes:
      - flipcount-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    image: ghcr.io/Marsellos/flip-count/flipcount-api:latest
    container_name: flipcount-api
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/flipcount
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 2507
    ports:
      - "8080:8080"

volumes:
  flipcount-db-data: